/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Controller;
import domain.Instruktor;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import session.Session;

/**
 *
 * @author Milan
 */
public class GlavnaForma extends javax.swing.JFrame {

    Instruktor instruktor;
    Thread counter_thread;

    /**
     * Creates new form MainForma
     */
    public GlavnaForma(Instruktor c) {
        initComponents();
        instruktor = c;
        setTitle(instruktor.getIme() + " " + instruktor.getPrezime());
        txtLogovan.setText("Ulogovani kao: " + instruktor.getIme());
        setResizable(false);
        setLocationRelativeTo(null);
        new_counter_thread();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtLogovan = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnEvidencijaKursa = new javax.swing.JButton();
        btnInstruktor = new javax.swing.JButton();
        btnPolaznik = new javax.swing.JButton();
        btnLicenca = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblTrajanjeSesije = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        txtLogovan.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtLogovan.setForeground(new java.awt.Color(255, 255, 255));
        txtLogovan.setText("Ulogovani kao: ");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Izloguj se");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnEvidencijaKursa.setBackground(new java.awt.Color(0, 204, 255));
        btnEvidencijaKursa.setForeground(new java.awt.Color(0, 0, 0));
        btnEvidencijaKursa.setText("Evidencija Kursa");
        btnEvidencijaKursa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvidencijaKursaActionPerformed(evt);
            }
        });

        btnInstruktor.setBackground(new java.awt.Color(0, 255, 0));
        btnInstruktor.setForeground(new java.awt.Color(0, 0, 0));
        btnInstruktor.setText("Instruktori");
        btnInstruktor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstruktorActionPerformed(evt);
            }
        });

        btnPolaznik.setBackground(new java.awt.Color(0, 255, 0));
        btnPolaznik.setForeground(new java.awt.Color(0, 0, 0));
        btnPolaznik.setText("Polaznici");
        btnPolaznik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPolaznikActionPerformed(evt);
            }
        });

        btnLicenca.setBackground(new java.awt.Color(255, 255, 255));
        btnLicenca.setForeground(new java.awt.Color(0, 0, 0));
        btnLicenca.setText("Licence");
        btnLicenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLicencaActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setOpaque(true);

        lblTrajanjeSesije.setBackground(new java.awt.Color(51, 51, 51));
        lblTrajanjeSesije.setForeground(new java.awt.Color(255, 255, 255));
        lblTrajanjeSesije.setText("Trajanje sesije: 0m 00s");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLicenca, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblTrajanjeSesije))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtLogovan, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnInstruktor, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                                .addComponent(btnEvidencijaKursa, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(btnPolaznik, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))))
            .addComponent(jSeparator1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogovan, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInstruktor)
                    .addComponent(btnEvidencijaKursa)
                    .addComponent(btnPolaznik))
                .addGap(18, 18, 18)
                .addComponent(btnLicenca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(lblTrajanjeSesije)
                .addContainerGap())
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int odgovor = JOptionPane.showConfirmDialog(this,
                "Da li ste sigurni da zelite da se odjavite?",
                "Odjava",
                JOptionPane.YES_NO_OPTION);

        if (odgovor == JOptionPane.NO_OPTION)
            return;
        else if (odgovor == JOptionPane.YES_OPTION) {
            try {
                String korisnickoIme = Session.getInstance().getUlogovani().getKorisnickoIme();
                Controller.getInstance().odjaviInstruktora(korisnickoIme);
                Session.getInstance().setUlogovani(null);
                LoginForma lf = new LoginForma();
                lf.setVisible(true);
                this.dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Greska prilikom odjave: " + ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEvidencijaKursaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvidencijaKursaActionPerformed
        // TODO add your handling code here:
        UpravljajEvidencijamaKursaForma pf = new UpravljajEvidencijamaKursaForma();
        pf.setVisible(true);
    }//GEN-LAST:event_btnEvidencijaKursaActionPerformed

    private void btnInstruktorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstruktorActionPerformed

        UpravljajInstruktorimaForma uif = new UpravljajInstruktorimaForma(instruktor);
        uif.setVisible(true);       
        
    }//GEN-LAST:event_btnInstruktorActionPerformed

    private void btnPolaznikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPolaznikActionPerformed
        try {
            // TODO add your handling code here:
            UpravljajPolaznicimaForma pkf = new UpravljajPolaznicimaForma();
            pkf.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPolaznikActionPerformed

    private void btnLicencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLicencaActionPerformed
        UpravljajLicencamaForma lf = new UpravljajLicencamaForma();
        lf.setVisible(true);      
    }//GEN-LAST:event_btnLicencaActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        counter_thread.interrupt();
    }//GEN-LAST:event_formWindowClosed

    
    public void new_counter_thread(){
        counter_thread = new Thread() {
            public void run() {
                int min = 0;
                int sec = 0;
                try {
                    while(true){
                        //System.out.println("m s "+min +sec);
                        lblTrajanjeSesije.setText("Trajanje sesije: " + min + "m " + sec + "s");
                        sec++;
                        if(sec==60){
                            sec=0;
                            min++;
                        }
                        sleep(1000);
                    }
                } catch(InterruptedException v) {
                    System.out.println(v);
                }
            }  

        };
        counter_thread.start();

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEvidencijaKursa;
    private javax.swing.JButton btnInstruktor;
    private javax.swing.JButton btnLicenca;
    private javax.swing.JButton btnPolaznik;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTrajanjeSesije;
    private javax.swing.JLabel txtLogovan;
    // End of variables declaration//GEN-END:variables
}
