/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Controller;
import domain.Instruktor;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import session.Session;

/**
 *
 * @author Milan
 */
public class GlavnaForma extends javax.swing.JFrame {

    Instruktor instruktor;

    /**
     * Creates new form MainForma
     */
    public GlavnaForma(Instruktor c) {
        initComponents();
        instruktor = c;
        setTitle(instruktor.getIme() + " " + instruktor.getPrezime());
        txtLogovan.setText("Zdravo, " + instruktor.getIme() + "!");
        setResizable(false);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtLogovan = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        meniInstruktor = new javax.swing.JMenu();
        itemInstruktorChange = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        itemSSAdd = new javax.swing.JMenuItem();
        itemSSControl = new javax.swing.JMenuItem();
        meniEvidencijaKursa = new javax.swing.JMenu();
        itemOtpAdd = new javax.swing.JMenuItem();
        itemOtpChange = new javax.swing.JMenuItem();
        itemOtpSearch = new javax.swing.JMenuItem();
        meniPolaznik = new javax.swing.JMenu();
        itemPolaznikAdd = new javax.swing.JMenuItem();
        itemPolaznikChange = new javax.swing.JMenuItem();
        meniTipCasa = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        meniMesto = new javax.swing.JMenu();
        itemMestoView = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setBackground(new java.awt.Color(153, 255, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Izloguj se");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtLogovan.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtLogovan.setText("jLabel1");

        meniInstruktor.setText("Instruktor");
        meniInstruktor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        itemInstruktorChange.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemInstruktorChange.setText("Kreiraj instruktora");
        itemInstruktorChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInstruktorChangeActionPerformed(evt);
            }
        });
        meniInstruktor.add(itemInstruktorChange);

        jMenuItem10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem10.setText("Upravljaj instruktorima");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        meniInstruktor.add(jMenuItem10);

        itemSSAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemSSAdd.setText("Ubaci licencu");
        itemSSAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSSAddActionPerformed(evt);
            }
        });
        meniInstruktor.add(itemSSAdd);

        itemSSControl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemSSControl.setText("Upravljaj licencama");
        itemSSControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSSControlActionPerformed(evt);
            }
        });
        meniInstruktor.add(itemSSControl);

        jMenuBar1.add(meniInstruktor);

        meniEvidencijaKursa.setText("EvidencijaKursa");
        meniEvidencijaKursa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        itemOtpAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemOtpAdd.setText("Kreiraj evidencijukursa");
        itemOtpAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOtpAddActionPerformed(evt);
            }
        });
        meniEvidencijaKursa.add(itemOtpAdd);

        itemOtpChange.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemOtpChange.setText("Upravljaj evidencijakursama");
        itemOtpChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOtpChangeActionPerformed(evt);
            }
        });
        meniEvidencijaKursa.add(itemOtpChange);

        itemOtpSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemOtpSearch.setText("Pretrazi evidencijukursa");
        itemOtpSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOtpSearchActionPerformed(evt);
            }
        });
        meniEvidencijaKursa.add(itemOtpSearch);

        jMenuBar1.add(meniEvidencijaKursa);

        meniPolaznik.setText("Polaznik");
        meniPolaznik.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        itemPolaznikAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemPolaznikAdd.setText("Kreiraj polaznika");
        itemPolaznikAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPolaznikAddActionPerformed(evt);
            }
        });
        meniPolaznik.add(itemPolaznikAdd);

        itemPolaznikChange.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemPolaznikChange.setText("Upravljaj polaznicima");
        itemPolaznikChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPolaznikChangeActionPerformed(evt);
            }
        });
        meniPolaznik.add(itemPolaznikChange);

        jMenuBar1.add(meniPolaznik);

        meniTipCasa.setText("TipCasa");
        meniTipCasa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem1.setText("Kreiraj tipCasa");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        meniTipCasa.add(jMenuItem1);

        jMenuItem14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem14.setText("Upravljaj tipCasaima");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        meniTipCasa.add(jMenuItem14);

        jMenuBar1.add(meniTipCasa);

        meniMesto.setText("Mesto");
        meniMesto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        itemMestoView.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemMestoView.setText("Pregled mesta");
        itemMestoView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMestoViewActionPerformed(evt);
            }
        });
        meniMesto.add(itemMestoView);

        jMenuBar1.add(meniMesto);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtLogovan, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLogovan, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemOtpAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOtpAddActionPerformed
        try {
            //throw new RuntimeException("Simulacija greske");
            KreirajEvidencijuKursaForma ko = new KreirajEvidencijuKursaForma();
            ko.setVisible(true);
            // tblOtp.setModel(mto);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem nije uspeo da kreira evidencijukursa!", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }

    }//GEN-LAST:event_itemOtpAddActionPerformed

    private void itemPolaznikChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPolaznikChangeActionPerformed
        try {
            // TODO add your handling code here:
            UpravljajPolaznicimaForma pkf = new UpravljajPolaznicimaForma(false);
            pkf.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_itemPolaznikChangeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int odgovor = JOptionPane.showConfirmDialog(this,
                "Da li ste sigurni da zelite da se odjavite?",
                "Odjava",
                JOptionPane.YES_NO_OPTION);

        if (odgovor == JOptionPane.NO_OPTION)
            return;
        else if (odgovor == JOptionPane.YES_OPTION) {
            try {
                String korisnickoIme = Session.getInstance().getUlogovani().getKorisnickoIme();
                Controller.getInstance().odjaviInstruktora(korisnickoIme);
                Session.getInstance().setUlogovani(null);
                LoginForma lf = new LoginForma();
                lf.setVisible(true);
                this.dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Greska prilikom odjave: " + ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void itemOtpChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOtpChangeActionPerformed
        // TODO add your handling code here:
        UpravljajEvidencijamaKursaForma pf = new UpravljajEvidencijamaKursaForma();
        pf.setVisible(true);
    }//GEN-LAST:event_itemOtpChangeActionPerformed

    private void itemPolaznikAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPolaznikAddActionPerformed
        // TODO add your handling code here:
        try {
            //throw new RuntimeException("Simulacija greske");
            KreirajPolaznikaForma kf = new KreirajPolaznikaForma();
            kf.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem nije uspeo da kreira polaznika!", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_itemPolaznikAddActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed

        UpravljajInstruktorimaForma pc = new UpravljajInstruktorimaForma(instruktor);
        pc.setVisible(true);

    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void itemInstruktorChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInstruktorChangeActionPerformed
        // TODO add your handling code here:
        KreirajInstruktoraForma kcf = new KreirajInstruktoraForma();
        kcf.setVisible(true);
    }//GEN-LAST:event_itemInstruktorChangeActionPerformed

    private void itemSSAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSSAddActionPerformed
        // TODO add your handling code here:
        UbaciLicencuForma ssf = new UbaciLicencuForma();
        ssf.setVisible(true);
    }//GEN-LAST:event_itemSSAddActionPerformed

    private void itemOtpSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOtpSearchActionPerformed
        // TODO add your handling code here:
        boolean pretraga = true;
        UpravljajEvidencijamaKursaForma uof = new UpravljajEvidencijamaKursaForma(pretraga);
        uof.setVisible(true);
    }//GEN-LAST:event_itemOtpSearchActionPerformed

    private void itemMestoViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMestoViewActionPerformed
        try {
            // TODO add your handling code here:
            PregledMestaForma pmf = new PregledMestaForma();
            pmf.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_itemMestoViewActionPerformed

    private void itemSSControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSSControlActionPerformed
        // TODO add your handling code here:
        UpravljajLicencamaForma pssf = new UpravljajLicencamaForma(instruktor);
        pssf.setVisible(true);
    }//GEN-LAST:event_itemSSControlActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        KreirajTipCasaForma kaf = new KreirajTipCasaForma();
        kaf.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        UpravljajTipovimaCasovaForma uaf = new UpravljajTipovimaCasovaForma();
        uaf.setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemInstruktorChange;
    private javax.swing.JMenuItem itemMestoView;
    private javax.swing.JMenuItem itemOtpAdd;
    private javax.swing.JMenuItem itemOtpChange;
    private javax.swing.JMenuItem itemOtpSearch;
    private javax.swing.JMenuItem itemPolaznikAdd;
    private javax.swing.JMenuItem itemPolaznikChange;
    private javax.swing.JMenuItem itemSSAdd;
    private javax.swing.JMenuItem itemSSControl;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenu meniEvidencijaKursa;
    private javax.swing.JMenu meniInstruktor;
    private javax.swing.JMenu meniMesto;
    private javax.swing.JMenu meniPolaznik;
    private javax.swing.JMenu meniTipCasa;
    private javax.swing.JLabel txtLogovan;
    // End of variables declaration//GEN-END:variables
}
