/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.Controller;
import domain.TipCasa;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import domain.Instruktor;
import domain.Polaznik;
import domain.EvidencijaKursa;
import domain.StavkaEvidencijeKursa;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
//import javax.swing.JTextField;
import tableModel.TableModelEvidencijaKursa;
import tableModel.TableModelStavkaEvidencijeKursa;
//import validator.Validator;

/**
 *
 * @author Milan
 */
public class KreirajEvidencijuKursaForma extends javax.swing.JDialog {

    private UpravljajEvidencijamaKursaForma uof;
    private EvidencijaKursa evidencijakursaInsert;
    private EvidencijaKursa evidencijakursaChange;
    private double ukupna = 0;

    public double getUkupna() {
        return ukupna;
    }

    public void setUkupna(double ukupna) {
        this.ukupna= ukupna;
    }

   
    public KreirajEvidencijuKursaForma() throws Exception {
        initComponents();
        this.evidencijakursaChange = null;
        setTitle("Kreiraj evidencijukursa");
        setResizable(false);
        setLocationRelativeTo(null);
        popuniInstruktoreIzBaze();
        popuniPolaznikeIzBaze();
        popuniTipCasaIzBaze();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        TableModelStavkaEvidencijeKursa tmodel = new TableModelStavkaEvidencijeKursa();
        //txtUkupno.setText(""+tmodel.getUkupnaCena());
        //tmodel.setKof(this);
        tableStavke.setModel(tmodel);
        JOptionPane.showMessageDialog(this, "Sistem je kreirao evidencijukursa!", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
    }

    public KreirajEvidencijuKursaForma(UpravljajEvidencijamaKursaForma parent, EvidencijaKursa evidencijakursa) throws Exception {

        this.uof = (UpravljajEvidencijamaKursaForma) parent;
        this.evidencijakursaChange = evidencijakursa;
        initComponents();
        setTitle("Promeni evidencijukursa");
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        popuniInstruktoreIzBaze();
        popuniPolaznikeIzBaze();
        popuniTipCasaIzBaze();
        popuniPromena(evidencijakursa);
        TableModelStavkaEvidencijeKursa tmodel = new TableModelStavkaEvidencijeKursa(evidencijakursa);
        //tmodel.setKof(this);
        tableStavke.setModel(tmodel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        comboTipCasa = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        chkZavrsen = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        txtCena = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboBoxInstruktor = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        comboBoxPolaznik = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNapomena = new javax.swing.JTextArea();
        btnDodajStavku = new javax.swing.JToggleButton();
        btnUkloniStavku = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableStavke = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtUkupno = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnOdustani = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                onWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        jLabel18.setBackground(new java.awt.Color(51, 51, 51));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("EvidencijaKursa");

        comboTipCasa.setBackground(new java.awt.Color(0, 204, 255));
        comboTipCasa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboTipCasa.setForeground(new java.awt.Color(0, 0, 0));
        comboTipCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipCasaActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TipCasa");

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Datum");

        txtDate.setBackground(new java.awt.Color(0, 0, 0));
        txtDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDate.setForeground(new java.awt.Color(255, 255, 255));
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Zavrsen");

        chkZavrsen.setBackground(new java.awt.Color(51, 51, 51));
        chkZavrsen.setForeground(new java.awt.Color(255, 255, 255));

        jLabel15.setBackground(new java.awt.Color(51, 51, 51));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Cena:");

        txtCena.setBackground(new java.awt.Color(0, 0, 0));
        txtCena.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCena.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Instruktor");

        comboBoxInstruktor.setBackground(new java.awt.Color(0, 204, 255));
        comboBoxInstruktor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboBoxInstruktor.setForeground(new java.awt.Color(0, 0, 0));
        comboBoxInstruktor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxInstruktorActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Polaznik");

        comboBoxPolaznik.setBackground(new java.awt.Color(0, 204, 255));
        comboBoxPolaznik.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboBoxPolaznik.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setOpaque(true);

        jLabel12.setBackground(new java.awt.Color(51, 51, 51));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Napomena");

        txtNapomena.setBackground(new java.awt.Color(0, 0, 0));
        txtNapomena.setColumns(20);
        txtNapomena.setForeground(new java.awt.Color(255, 255, 255));
        txtNapomena.setRows(5);
        txtNapomena.setPreferredSize(new java.awt.Dimension(0, 0));
        jScrollPane2.setViewportView(txtNapomena);

        btnDodajStavku.setBackground(new java.awt.Color(0, 255, 0));
        btnDodajStavku.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDodajStavku.setForeground(new java.awt.Color(0, 0, 0));
        btnDodajStavku.setText("Dodaj stavku");
        btnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkuActionPerformed(evt);
            }
        });

        btnUkloniStavku.setBackground(new java.awt.Color(255, 0, 0));
        btnUkloniStavku.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUkloniStavku.setForeground(new java.awt.Color(0, 0, 0));
        btnUkloniStavku.setText("Ukloni stavku");
        btnUkloniStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUkloniStavkuActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator2.setOpaque(true);

        jLabel13.setBackground(new java.awt.Color(51, 51, 51));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Stavke evidencijekursa");

        tableStavke.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableStavke);

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ukupan iznos");

        txtUkupno.setBackground(new java.awt.Color(0, 0, 0));
        txtUkupno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUkupno.setForeground(new java.awt.Color(255, 255, 255));
        txtUkupno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUkupnoActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(0, 255, 0));
        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(0, 0, 0));
        btnSave.setText("Sacuvaj");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnOdustani.setBackground(new java.awt.Color(255, 255, 255));
        btnOdustani.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnOdustani.setForeground(new java.awt.Color(0, 0, 0));
        btnOdustani.setText("Otkazi");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator3.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnDodajStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkZavrsen)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboTipCasa, 0, 192, Short.MAX_VALUE)
                                    .addComponent(txtDate))
                                .addGap(26, 26, 26)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel13)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUkloniStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBoxInstruktor, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBoxPolaznik, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(comboBoxInstruktor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxPolaznik, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboTipCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(chkZavrsen))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnDodajStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUkloniStavku))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOdustani)
                    .addComponent(btnSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuActionPerformed
        if (txtDate.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nisu sva polja popunjena za tipCasa!", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }

        TipCasa tc = (TipCasa) comboTipCasa.getSelectedItem();
        DateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date datumPrisustva;
        try {
            datumPrisustva = sdf.parse(txtDate.getText().trim());
            
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this,"Nije pravilo popunjen datum! Format je: yyyy-mm-dd", "Greska", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(KreirajEvidencijuKursaForma.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }

        double cena = Math.floor(Double.parseDouble(txtCena.getText()) * 100.0) / 100.0;
        String napomena = txtNapomena.getText();
        TableModelStavkaEvidencijeKursa tmodel = (TableModelStavkaEvidencijeKursa) tableStavke.getModel();
        StavkaEvidencijeKursa s1;
        if (evidencijakursaChange == null) {
            s1 = new StavkaEvidencijeKursa(-1, datumPrisustva, napomena, chkZavrsen.isSelected(), tc, evidencijakursaInsert);
        } else {
            s1 = new StavkaEvidencijeKursa(-1, datumPrisustva, napomena, chkZavrsen.isSelected(), tc, evidencijakursaChange);
        }

        tmodel.dodajStavkuEvidencijeKursa(s1);
        tableStavke.setModel(tmodel);
        resetPodataka();
        
        ukupna = tmodel.getUkupnaCena();
        txtUkupno.setText(ukupna + "");
    }//GEN-LAST:event_btnDodajStavkuActionPerformed

    private void comboTipCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipCasaActionPerformed
        TipCasa a = (TipCasa) comboTipCasa.getSelectedItem();
        txtCena.setText(a.getCena() + "");
    }//GEN-LAST:event_comboTipCasaActionPerformed

    private void btnUkloniStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUkloniStavkuActionPerformed
        // TODO add your handling code here:
        int selected = tableStavke.getSelectedRow();
        if (selected == -1) {
            JOptionPane.showMessageDialog(this, "Nista nije selektovano iz tabele", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        TableModelStavkaEvidencijeKursa tmodel = (TableModelStavkaEvidencijeKursa) tableStavke.getModel();
        tmodel.obrisiStavkuEvidencijeKursa(selected);
        tableStavke.setModel(tmodel);
        
        //TODO txtCena.setText(tmodel.getCena() + "");
        ukupna = tmodel.getUkupnaCena();
        txtUkupno.setText(ukupna+"");

    }//GEN-LAST:event_btnUkloniStavkuActionPerformed

    private void comboBoxInstruktorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxInstruktorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxInstruktorActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void onWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onWindowClosed
        UpravljajEvidencijamaKursaForma f = new UpravljajEvidencijamaKursaForma();
        f.setVisible(true);
    }//GEN-LAST:event_onWindowClosed

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnOdustaniActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Instruktor c = (Instruktor) comboBoxInstruktor.getSelectedItem();
        Polaznik k = (Polaznik) comboBoxPolaznik.getSelectedItem();

        if (evidencijakursaChange == null) {
            try {
                TableModelStavkaEvidencijeKursa tmodel = (TableModelStavkaEvidencijeKursa) tableStavke.getModel();
                ArrayList<StavkaEvidencijeKursa> stavke = tmodel.getListaStavki();
                evidencijakursaInsert = new EvidencijaKursa(-1, ukupna,  c, k, stavke);
                System.out.println("otp:"+evidencijakursaInsert);

                Controller.getInstance().dodajEvidencijuKursa(evidencijakursaInsert);
                JOptionPane.showMessageDialog(this, "Sistem je sacuvao evidencijukursa!", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da sacuva evidencijukursa!", "Greska", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        } else {
            try {
                //throw new RuntimeException("Simulacija greske");
                TableModelStavkaEvidencijeKursa tmodel = (TableModelStavkaEvidencijeKursa) tableStavke.getModel();
                //tmodel.setKof(this);
                ArrayList<StavkaEvidencijeKursa> stavke = tmodel.getListaStavki();

                evidencijakursaChange.setInstruktor(c);
                evidencijakursaChange.setPolaznik(k);
                evidencijakursaChange.setUkupanIznos(ukupna);
                evidencijakursaChange.setStavkeEvidencijeKursa(stavke);

                Controller.getInstance().promeniEvidencijuKursa(evidencijakursaChange);

                JOptionPane.showMessageDialog(this, "Sistem je izmenio evidencijukursa!", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
                uof.getTblOtp().setModel(new TableModelEvidencijaKursa());
                this.dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da izmeni evidencijukursa!", "Greska", JOptionPane.ERROR_MESSAGE);
                //return;
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtUkupnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUkupnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUkupnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnDodajStavku;
    private javax.swing.JButton btnOdustani;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUkloniStavku;
    private javax.swing.JCheckBox chkZavrsen;
    private javax.swing.JComboBox<domain.Instruktor> comboBoxInstruktor;
    private javax.swing.JComboBox<domain.Polaznik> comboBoxPolaznik;
    private javax.swing.JComboBox<domain.TipCasa> comboTipCasa;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable tableStavke;
    private javax.swing.JTextField txtCena;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextArea txtNapomena;
    private javax.swing.JTextField txtUkupno;
    // End of variables declaration//GEN-END:variables

    private void popuniInstruktoreIzBaze() throws Exception {

        txtCena.setEnabled(false);
        txtUkupno.setEnabled(false);
        comboBoxPolaznik.removeAllItems();
        ArrayList<Instruktor> instruktori = Controller.getInstance().ucitajInstruktoreIzBaze();
        for (Instruktor c : instruktori) {
            comboBoxInstruktor.addItem(c);
        }
    }

    private void popuniPolaznikeIzBaze() throws Exception {
        comboBoxPolaznik.removeAllItems();
        ArrayList<Polaznik> polaznici = Controller.getInstance().ucitajPolaznikeIzBaze();
        for (Polaznik k : polaznici) {
            comboBoxPolaznik.addItem(k);
        }
    }

    private void popuniTipCasaIzBaze() throws Exception {
        comboTipCasa.removeAllItems();
        ArrayList<TipCasa> tipCasai = Controller.getInstance().ucitajTipCasaeIzBaze();
        for (TipCasa a : tipCasai) {
            comboTipCasa.addItem(a);
        }
    }

    private void resetPodataka() {
        txtCena.setText("");
        txtDate.setText("");
        txtNapomena.setText("");
    }

    private void popuniPromena(EvidencijaKursa evidencijakursa) {
        try {
            ukupna = evidencijakursa.getUkupanIznos();
            comboBoxInstruktor.setSelectedItem(evidencijakursa.getInstruktor());
            comboBoxPolaznik.setSelectedItem(evidencijakursa.getPolaznik());
            txtUkupno.setText(evidencijakursa.getUkupanIznos() + "");
            tableStavke.setModel(new TableModelStavkaEvidencijeKursa(evidencijakursa));
        } catch (Exception ex) {
            Logger.getLogger(KreirajEvidencijuKursaForma.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
