/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Controller;
import domain.Instruktor;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.Document;
import session.Session;

/**
 *
 * @author Milan
 */
public class LoginForma extends javax.swing.JFrame {

    /**
     * Creates new form LoginForma
     */
    public LoginForma() {

        initComponents();
        setTitle("Prijava");
        setResizable(false);
        setLocationRelativeTo(null);
        txtErrorLozinka.setVisible(false);
        unos();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblkorisnickoIme = new javax.swing.JLabel();
        lblLoznika = new javax.swing.JLabel();
        txtKorisnickoIme = new javax.swing.JTextField();
        txtLozinka = new javax.swing.JPasswordField();
        txtErrorLozinka = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnUlogujSe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        lblkorisnickoIme.setBackground(new java.awt.Color(51, 51, 51));
        lblkorisnickoIme.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblkorisnickoIme.setForeground(new java.awt.Color(255, 255, 255));
        lblkorisnickoIme.setText("Korisnicko ime:");

        lblLoznika.setBackground(new java.awt.Color(51, 51, 51));
        lblLoznika.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLoznika.setForeground(new java.awt.Color(255, 255, 255));
        lblLoznika.setText("Lozinka");

        txtKorisnickoIme.setBackground(new java.awt.Color(0, 0, 0));
        txtKorisnickoIme.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtKorisnickoIme.setForeground(new java.awt.Color(255, 255, 255));
        txtKorisnickoIme.setText("admin");
        txtKorisnickoIme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKorisnickoImeActionPerformed(evt);
            }
        });

        txtLozinka.setBackground(new java.awt.Color(0, 0, 0));
        txtLozinka.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLozinka.setForeground(new java.awt.Color(255, 255, 255));
        txtLozinka.setText("admin");
        txtLozinka.setEchoChar('*');
        txtLozinka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLozinkaActionPerformed(evt);
            }
        });

        txtErrorLozinka.setBackground(new java.awt.Color(51, 51, 51));
        txtErrorLozinka.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtErrorLozinka.setForeground(new java.awt.Color(255, 0, 0));
        txtErrorLozinka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtErrorLozinkaActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(255, 255, 255));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(0, 0, 0));
        btnCancel.setText("Otkazi");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnUlogujSe.setBackground(new java.awt.Color(0, 255, 0));
        btnUlogujSe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUlogujSe.setForeground(new java.awt.Color(0, 0, 0));
        btnUlogujSe.setText("Uloguj se");
        btnUlogujSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUlogujSeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblkorisnickoIme)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(btnUlogujSe, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblLoznika, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtKorisnickoIme, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(txtLozinka)
                            .addComponent(txtErrorLozinka))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblkorisnickoIme))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoznika)
                    .addComponent(txtLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtErrorLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUlogujSe)
                    .addComponent(btnCancel))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKorisnickoImeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKorisnickoImeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKorisnickoImeActionPerformed

    private void txtLozinkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLozinkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLozinkaActionPerformed

    private void btnUlogujSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUlogujSeActionPerformed
        // TODO add your handling code here:
        try {
            if (txtKorisnickoIme.getText().isEmpty() || String.valueOf(txtLozinka.getPassword()).isEmpty()) {
                JOptionPane.showMessageDialog(this, "Sva polja moraju biti popunjena!",
                        "Popunite polja", JOptionPane.WARNING_MESSAGE);
            }
            Controller controller = Controller.getInstance();
            String user = txtKorisnickoIme.getText();
            String pass = String.valueOf(txtLozinka.getPassword());
            Instruktor instruktor = new Instruktor();
            instruktor.setKorisnickoIme(user);
            instruktor.setLozinka(pass);
            instruktor = controller.prijaviInstruktora(instruktor);
            try {
                // throw new RuntimeException("Simulacija greske");
                JOptionPane.showMessageDialog(this, "Korisnicko ime i sifra su ispravni!", "Login", JOptionPane.INFORMATION_MESSAGE);
                Session.getInstance().setUlogovani(instruktor);
                GlavnaForma gf = new GlavnaForma(instruktor);
                gf.setVisible(true);
                this.dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ne moze da se otvori glavna forma meni", "Greska", JOptionPane.ERROR_MESSAGE);
                Controller.getInstance().odjaviInstruktora(instruktor.getKorisnickoIme());
            }
        } catch (RuntimeException re) {
            JOptionPane.showMessageDialog(this, re.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUlogujSeActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtErrorLozinkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtErrorLozinkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtErrorLozinkaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnUlogujSe;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLoznika;
    private javax.swing.JLabel lblkorisnickoIme;
    private javax.swing.JTextField txtErrorLozinka;
    private javax.swing.JTextField txtKorisnickoIme;
    private javax.swing.JPasswordField txtLozinka;
    // End of variables declaration//GEN-END:variables

    private void unos() {
        MyDocumentListener listener = new MyDocumentListener();
        txtKorisnickoIme.getDocument().addDocumentListener(listener);
        txtLozinka.getDocument().addDocumentListener(listener);
    }

    public class MyDocumentListener implements DocumentListener {

        @Override
        public void insertUpdate(DocumentEvent e) {
            validate(e);
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            validate(e);
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            validate(e);
        }

        private void validate(DocumentEvent e) {
            Document source = e.getDocument();

            if (source == txtKorisnickoIme.getDocument()) {
                txtErrorLozinka.setText("");
                txtErrorLozinka.setVisible(false);

            }
            if (source == txtLozinka.getDocument()) {
                String pass = String.valueOf(txtLozinka.getPassword());
                if (pass != null && pass.length() >= 8) {
                    txtErrorLozinka.setText("");
                    txtErrorLozinka.setVisible(false);

                } else {
                    txtErrorLozinka.setVisible(true);
                    txtErrorLozinka.setText("Nedovoljno karaktera lozinke!");
                }
            }
            txtErrorLozinka.getParent().revalidate();
        }

    }
}
