/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import communication.Communication;
import communication.Operation;
import controller.Controller;
import form.polaznik.AddPolaznikForm;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mmmdeb
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        PolaznikPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        DodajPolaznikaButton = new javax.swing.JButton();
        PromeniPolaznikaButton = new javax.swing.JButton();
        ObrisiPolaznikaButton = new javax.swing.JButton();
        KursPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        DodajPolaznikaButton.setText("Додај Полазника");
        DodajPolaznikaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DodajPolaznikaButtonActionPerformed(evt);
            }
        });

        PromeniPolaznikaButton.setText("Промени Полазника");
        PromeniPolaznikaButton.setEnabled(false);

        ObrisiPolaznikaButton.setText("Обриши Полазника");
        ObrisiPolaznikaButton.setEnabled(false);
        ObrisiPolaznikaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObrisiPolaznikaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PolaznikPanelLayout = new javax.swing.GroupLayout(PolaznikPanel);
        PolaznikPanel.setLayout(PolaznikPanelLayout);
        PolaznikPanelLayout.setHorizontalGroup(
            PolaznikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PolaznikPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addGroup(PolaznikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DodajPolaznikaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PromeniPolaznikaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ObrisiPolaznikaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        PolaznikPanelLayout.setVerticalGroup(
            PolaznikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PolaznikPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(PolaznikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PolaznikPanelLayout.createSequentialGroup()
                        .addComponent(DodajPolaznikaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PromeniPolaznikaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ObrisiPolaznikaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Polaznik", PolaznikPanel);

        javax.swing.GroupLayout KursPanelLayout = new javax.swing.GroupLayout(KursPanel);
        KursPanel.setLayout(KursPanelLayout);
        KursPanelLayout.setHorizontalGroup(
            KursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );
        KursPanelLayout.setVerticalGroup(
            KursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Kurs", KursPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Polaznik");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ObrisiPolaznikaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObrisiPolaznikaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ObrisiPolaznikaButtonActionPerformed

    private void DodajPolaznikaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DodajPolaznikaButtonActionPerformed
        // TODO add your handling code here:
        AddPolaznikForm apf;
        try {
            apf = new AddPolaznikForm();
            apf.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_DodajPolaznikaButtonActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DodajPolaznikaButton;
    private javax.swing.JPanel KursPanel;
    private javax.swing.JButton ObrisiPolaznikaButton;
    private javax.swing.JPanel PolaznikPanel;
    private javax.swing.JButton PromeniPolaznikaButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
