/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import thread.ThreadServer;

/**
 *
 * @author Milan
 */
public class ServerForm extends javax.swing.JFrame {

    private ThreadServer threadServer;

    /**
     * Creates new form ServerskaForma
     */
    public ServerForm() {
        initComponents();
        setLocationRelativeTo(null);
        lblServerStatus.setText("Server je ugasen!");
        btnPokreniServer.setEnabled(true);
        btnUgasiServer.setEnabled(false);
        setResizable(false);
        setTitle("Serverska forma");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnUgasiServer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnPokreniServer = new javax.swing.JButton();
        lblServerStatus = new javax.swing.JLabel();
        btnKonfiguracija = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        btnUgasiServer.setBackground(new java.awt.Color(255, 0, 0));
        btnUgasiServer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUgasiServer.setForeground(new java.awt.Color(0, 0, 0));
        btnUgasiServer.setText("UGASI SERVER");
        btnUgasiServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUgasiServerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("STATUS:");

        btnPokreniServer.setBackground(new java.awt.Color(0, 255, 0));
        btnPokreniServer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPokreniServer.setForeground(new java.awt.Color(0, 0, 0));
        btnPokreniServer.setText("POKRENI SERVER");
        btnPokreniServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokreniServerActionPerformed(evt);
            }
        });

        lblServerStatus.setBackground(new java.awt.Color(255, 255, 255));
        lblServerStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblServerStatus.setForeground(new java.awt.Color(255, 255, 255));

        btnKonfiguracija.setBackground(new java.awt.Color(255, 255, 255));
        btnKonfiguracija.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnKonfiguracija.setForeground(new java.awt.Color(0, 0, 0));
        btnKonfiguracija.setText("KONFIGURACIJA");
        btnKonfiguracija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfiguracijaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(btnPokreniServer, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(btnUgasiServer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKonfiguracija, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblServerStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(btnPokreniServer, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKonfiguracija, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUgasiServer, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblServerStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUgasiServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUgasiServerActionPerformed
        if (threadServer.getServerSocket() != null && threadServer.getServerSocket().isBound()) {
            try {
                threadServer.getServerSocket().close();
                JOptionPane.showMessageDialog(this, "Server je ugasen, gasenje programa...");
                this.dispose();
                System.exit(0);
            } catch (IOException ex) {
                Logger.getLogger(ServerForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnUgasiServerActionPerformed

    private void btnPokreniServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokreniServerActionPerformed
        // TODO add your handling code here:
                File file = new File("dbconfiguration.properties");
        if (!file.exists()) {
            JOptionPane.showMessageDialog(this, "Konfiguracioni fajl ne postoji!"
                + "Unesite parametre za pristup bazi podataka!", "Upozorenje", JOptionPane.ERROR_MESSAGE);
            new KonfiguracijaBaze(this, true).setVisible(true);
        }

        if (file.exists()) {
            if (threadServer == null || !threadServer.isAlive()) {
                threadServer = new ThreadServer();
                threadServer.start();
                lblServerStatus.setText("Server je pokrenut");
                btnUgasiServer.setEnabled(true);
                btnPokreniServer.setEnabled(false);
            }else{
                JOptionPane.showMessageDialog(this, "Port se vec koristi. Samo jedan server se moze pokrenuti", "Greska", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnPokreniServerActionPerformed

    private void btnKonfiguracijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfiguracijaActionPerformed
        // TODO add your handling code here:
        new KonfiguracijaBaze(this, true).setVisible(true);
    }//GEN-LAST:event_btnKonfiguracijaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKonfiguracija;
    private javax.swing.JButton btnPokreniServer;
    private javax.swing.JButton btnUgasiServer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblServerStatus;
    // End of variables declaration//GEN-END:variables

}
